import Head from 'next/head';
import Image from 'next/image';
import { Lato } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { BaseSyntheticEvent, KeyboardEvent, useState } from 'react';
import Commander from '@/components/Commander/Commaner';

const lato = Lato({ subsets: ['latin'], weight: '400' });

export default function Home() {
  const [inputVal, setInputVal] = useState('');

  const handleSubmit = (e: BaseSyntheticEvent) => {
    e.preventDefault();
    alert('submit');
  };

  const handleKeyPress = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter') {
      handleSubmit(e);
    }
  };

  return (
    <>
      <Head>
        <title>MMCoding</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main className={`${styles.main} ${lato.className}`}>
        <Commander />
        <form onSubmit={() => handleSubmit}>
          <label>visitor@mmcoding.com:~$&nbsp;</label>
          <textarea
            value={inputVal}
            onChange={(e) => setInputVal(e.target.value)}
            onKeyDown={(e) => handleKeyPress(e)}
          />
        </form>
      </main>
    </>
  );
}
